name: e2e Test

on:
  push:
    tags: 'v*.*'

env:
  REGISTRY: ${{secrets.DOCKER_REGISTRY}}
  TAG: $REGISTRY/${{ github.event.repository.name }}/${{ github.ref_name }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Build and push
        uses: docker/build-push-action@v6
        env: |
          TAG: $TAG
        with:
          push: true
          tags: $TAG
