name: e2e Test

on:
  pull_request:

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup env
        env:
          ENV: ${{ var.env }}
        run: |
          echo $ENV

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: yarn
      - run: yarn test

    
